# Generated by Django 3.2.18 on 2023-04-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='support_description',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='title'),
        ),
    ]
