# Generated by Django 3.2.18 on 2023-04-21 14:34

from django.db import migrations, models
import django.db.models.deletion
import techsupport.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('techsupport', '0002_auto_20230417_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSocialAccount',
            fields=[
                ('socialaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialaccount.socialaccount')),
            ],
            bases=(techsupport.models.RolePermissionMixin, 'socialaccount.socialaccount'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=30, verbose_name='status'),
        ),
    ]
