# Generated by Django 3.2.18 on 2023-04-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0002_auto_20230414_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='centre',
            options={'verbose_name_plural': 'centres'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name_plural': 'regions'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'subcategories'},
        ),
    ]
