# Generated by Django 4.2.2 on 2023-07-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0002_remove_user_dark_mode_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='centres',
            field=models.ManyToManyField(related_name='users', to='techsupport.centre'),
        ),
    ]
