# Generated by Django 4.2.7 on 2023-11-16 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0003_remove_supportticket_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='date_archived',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date archived'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
