# Generated by Django 4.2.2 on 2023-07-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0006_alter_supportticket_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
    ]
