# Generated by Django 4.2.2 on 2023-07-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0007_supportticket_resolution_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=30, verbose_name='priority'),
        ),
    ]
