# Generated by Django 4.2.2 on 2023-07-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0008_alter_supportticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='users', to='techsupport.region'),
        ),
    ]
