# Generated by Django 4.2.2 on 2023-07-21 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0009_user_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='regions',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='assigned to'),
        ),
    ]
