# Generated by Django 4.2.2 on 2023-07-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0011_user_country_user_region_alter_category_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=30, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=30, verbose_name='status'),
        ),
    ]
