# Generated by Django 3.2.18 on 2023-09-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0013_auto_20230829_1421'),
        ('techsupport', '0013_auto_20230901_0902'),
    ]

    operations = [
    ]
