# Generated by Django 3.2.18 on 2023-09-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0014_merge_0013_auto_20230829_1421_0013_auto_20230901_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
