name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Environment Variables
      run: |
        echo "TSUPPORT_SECRET_KEY=mydummysecretkey" >> $GITHUB_ENV
        echo "TSUPPORT_SITE_ID=1" >> $GITHUB_ENV
        echo "DEBUG=True" >> $GITHUB_ENV
        echo "EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend" >> $GITHUB_ENV
        echo "EMAIL_HOST=mydummyemailhost" >> $GITHUB_ENV
        echo "EMAIL_PORT=587" >> $GITHUB_ENV
        echo "EMAIL_USE_TLS=True" >> $GITHUB_ENV
        echo "EMAIL_HOST_USER=mydummyemailuser" >> $GITHUB_ENV
        echo "EMAIL_HOST_PASSWORD=mydummyemailpassword" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_ID=mydummyclientid" >> $GITHUB_ENV
        echo "GOOGLE_CLIENT_SECRET=mydummyclientsecret" >> $GITHUB_ENV
        echo "GOOGLE_API_KEY=mydummyapikey" >> $GITHUB_ENV
        echo "GOOGLE_CHAT_WEB_HOOK_URL=mydummywebhookurl" >> $GITHUB_ENV

    - name: Run Tests
      run: |
        python manage.py test
